### ISSUE TITLE
bot doesn't log in: discord.errors.LogInFailure: Improper token has been passed.

### ISSUE THREAD

**Issue by AndrewBohler** [AndrewBohler/DiscordBot#1]
Have tried regenerating a new token but still getting this error.
```
Traceback (most recent call last):
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "DiscordBot.py", line 156, in <module>
    client.run(TOKEN)
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "C:\Users\Drew\Anaconda3\envs\discord\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002EFF47DC1D0>
```

**Comment by AndrewBohler** [comment]
This seems to be an issue on windows as running it on linux works just fine. If I just paste in the token as a string then it works. It doesn't like looking up the environment variable even though if I `print(os.environ('DISCORD_TOKEN'))` the correct token is printed to stdout.

**Comment by AndrewBohler** [comment]
So it seems that in windows `set VARIABLE="variable"` actually includes the quotes.
So the right syntax is `set VARIABLE=variable`
